language: node_js
node_js:
- '7.6'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang

before_install:
- export CXX="g++-4.8"
- export CC="gcc-4.8"

before_script:
- npm install

script:
- npm test

after_success: bash ./bin/deploy.sh

env:
  global:
  - GIT_USER: Travis CI
  - GIT_EMAIL: kamataryo@users.noreply.github.com
  - GH_REF: github.com/kamataryo/torimap.git
  secure: "M7fJ9lMJ5ANAjvlWWRWe8YzQf4GAovfbBBYHgbR1/uHJnoAdk2VCft1/8gZo1lNkGALFTA08eHhrNGJvWAOyfCqLXP8kO5viQhKwQ3QBpiXYzVxK6kstRvnYXrnde9mPuYDFn2Y6AyfeUbYfZ/UxdielycLDS6e71shqHkbu3Tw9V9NZB61pQdtLxgFueZc/MJzeWWJeAE5Gc5wOQdyRlLwm0N5JqILUdtEGPblKDBGf3ICM3LC6O6WBjYzs7k+LVo5y2kblDQUEEMQIg9V441o/QSHgc5VIR2GJWSIOJv2UVy+5WxR52OlzYGJw22wVdD5/3LVzCANpylUchSnrXy4QziIB7+vnBJ2hgCXqtYi4eUlUpQnjA8Eto1/4Z1Cgs+cXj9zeg1iJPNWYPJkCFp4w1dlrkNlu+a7nMpGfHlHk9ofxkyoYNTEkbhHbF/98QCUyWVZQtSv+p+6NxhZGnh7kkMHeJyZNTZAzMDDb72+mwEtFSZOOmYh0xY9maDKToRxAVTobRoVIkDaTXMmKjPnX92yY45uIl+XbqJ0I28AUia7RTYCCU/bZm38umAYLKT9+XUCuVaBfqpQ1w8nAhmf5uZVTapyg3ZvCt3w3vbmtp+uEx2c9qUYokFohf5KURldGEhv52KaEGqBVvV2fm+sE7NE6+3IxYsEqrWcHYqQ="
