language: node_js
node_js:
- '7.6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
before_install:
- export CXX="g++-4.8"
- export CC="gcc-4.8"
before_script:
- npm install
script:
- npm test
after_success: bash ./bin/deploy.sh
env:
  global:
  - GIT_USER: "Travis CI"
  - GIT_EMAIL: kamataryo@users.noreply.github.com
  - GH_REF: github.com/KamataRyo/torimap.git
  - secure: PZZukKj6AjXXgNpHrLmnLTd5o1s48foxAzljg1vNva1r8mjEauX0cLNEbFrAjbOK1peYdMpn+XLC0ssM8E917VpNit78wpDtLuoxZ0zUYyUFFm1RolJYs2kx5vPj/HdbDKvPqCO+Xp578f13AllqG64uFalz8HnV9ottZ8FKRWnCJady6p7oQtNIllOb75Jv4JKMpnkdN80jqRAFLYdDS4Xekv+NjHJXBMl+TenyCML72ehCz9dOKulMqot7d41+hwIroC9PyYg8hReKBfhQLsYWn/APFGvzVJX96NWCoUtocTkJVA5Y36WUQY7BOztF/5mROuc2mHkyp136dQYDHUa1U6ex/0EoN5Myu6WuEIQlqzPXteoiDHoqGnMMzooknvajKZshjo6H8I0ar6kTFq2PNDfcgW3G0/vO4rz56OGpPPfVupgkGBmpO3dPPYm1f5aLdHvJ1SJ3BnV2MW4tibQWGOxOmYU/kjt90FVaWzQz/0RnQp1x/u7OYTGin+jve/pIHmh1kdLZdZdrfMbvM/lGYGyQy7ohHuKJUtX51p8GrZo8kMqUtmXGTOJXOOcgjFn2hTPKjpb8V8NUkPLtnhjwrhK1XCM62Y6zhW4aeEjFLByypBkaOGMNo5yCX3bjlEHwmGQqS3K8wr26k7M5kC0iGYTIdC2bpIG47fE3tcw=
