language: node_js
node_js:
- '7.6'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
before_install:
- export CXX="g++-4.8"
- export CC="gcc-4.8"
before_script:
- npm install
script:
- npm test
after_success: bash ./bin/deploy.sh
env:
  global:
  - GIT_USER: "Travis CI"
  - GIT_EMAIL: kamataryo@users.noreply.github.com
  - GH_REF: github.com/KamataRyo/torimap.git
  - secure: "uFRQyHaOUrAQQWqJ9AVTfWDmNS80kq6oqc9uZI6YMTCbGI2Ab8L5e7s1IPUhL6fFwIHtmWxJBvxexERe7Swlhk0q5T4Su3aq9tuhSdJPax8g8xTl8xrv3Qe3xkvP/saCaZijf3rJH77pa0VZ8tI5FHA3PtfKxelAaXxjAtPxID0ramhDRrYz1Jzh7e0GG0KPIKcRXh3b9b7mb7e6YN3MXaPc3ANjZMiggSjnjKM1E/M7cOFci9KD+cOGq91hWksf4rY0XOQdjg8OGFS2oGFs/ByEnd86L7o9oydxD1YU0kGsgAqD3H7TYjXYHJFlFkx0fXhkrYUSx7FE98cnSVhg1QylSyxaZ5VgVjKfLHg/XIGkrzUwzej10Be/tBWCY2q3zay6+DJb3jEeLVO6j4UwN6MG7oKrqJcF7YcCK2abBzhfdNh/6v6+grvYCQeoEHOrCKAmM056griZ8GM0MVi4DQr9mN7HfdUuJijfnHHZSVvlBMW2biP3gzj1F8LeZZ4Y2rG1JZ4Cfq8VP6bhdG+qvN0E+TfMF5g48iuKgrN1LpH7yB1kZ9siTrwKTEVMaEmsMEn2QBvR/neRDhNhRm2xLeC1IcJItqEZVc05njsnK56xs4JBOjW1fa3Y6E4i20fYHEOj/oz1qQWFYUR903LJR1r+iX0DzzVICuj78GgH7zY="
